# Build stage
FROM node:20-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine
# Copy built assets from build-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Note: nginx.conf will be mounted via docker-compose
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
