"""Add Entity model and Complaint fields

Revision ID: 49e65ca57ac1
Revises: 
Create Date: 2026-05-27 23:16:39.461358

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49e65ca57ac1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_value', sa.Text(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.alter_column('agents', 'email',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('agents', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'agent'::character varying"))
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('complaint_embeddings', 'complaint_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('complaint_messages', 'complaint_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('complaint_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('complaints', sa.Column('next_best_action', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('incident_group_id', sa.String(length=100), nullable=True))
    op.alter_column('complaints', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('complaints', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('complaints', 'is_sla_breached',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('complaints', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_complaints_external_id'), 'complaints', ['external_id'], unique=False)
    op.create_index(op.f('ix_complaints_incident_group_id'), 'complaints', ['incident_group_id'], unique=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalations', 'complaint_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('escalations', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('escalations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sla_configs', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('sla_configs', 'max_resolution_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sla_configs', 'escalation_threshold_pct',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('80'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sla_configs', 'escalation_threshold_pct',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('80'))
    op.alter_column('sla_configs', 'max_resolution_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sla_configs', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('escalations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalations', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('escalations', 'complaint_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_complaints_incident_group_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_external_id'), table_name='complaints')
    op.alter_column('complaints', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('complaints', 'is_sla_breached',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('complaints', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('complaints', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_column('complaints', 'incident_group_id')
    op.drop_column('complaints', 'next_best_action')
    op.alter_column('complaint_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('complaint_messages', 'complaint_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('complaint_embeddings', 'complaint_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'agent'::character varying"))
    op.alter_column('agents', 'email',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
