"""Add indexes

Revision ID: a27691e4b122
Revises: b3b230bbc2dc
Create Date: 2026-07-01 03:57:07.387881

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a27691e4b122'
down_revision: Union[str, None] = 'b3b230bbc2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'body',
               existing_type=sa.TEXT(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index(op.f('ix_complaints_channel'), 'complaints', ['channel'], unique=False)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_severity'), 'complaints', ['severity'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.drop_constraint('customers_email_hash_key', 'customers', type_='unique')
    op.drop_constraint('customers_email_key', 'customers', type_='unique')
    op.create_index(op.f('ix_customers_email_hash'), 'customers', ['email_hash'], unique=True)
    op.alter_column('entities', 'entity_value',
               existing_type=sa.TEXT(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entities', 'entity_value',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_customers_email_hash'), table_name='customers')
    op.create_unique_constraint('customers_email_key', 'customers', ['email'])
    op.create_unique_constraint('customers_email_hash_key', 'customers', ['email_hash'])
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_severity'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_channel'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.alter_column('complaints', 'body',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
